# fly.toml app configuration file generated for fastapi-ci-demo on 2025-08-05T15:35:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-ci-demo'
primary_region = 'fra'

[build]
image = "ghcr.io/michael-aga/fastapi-ci-demo:latest"

[registry]
  auth_token = "GHCR_TOKEN"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
